keys:
  - &primary age1yrdymrnkmwpf4q4krfp2tsm9lelm4mfvek4sqz8umg8vwlaxagsq63nk2m
  - &bitskey age1ede7hsjj03xssxrt3dlrlw927znlgw4tk3vy6akeajwtgnu02ddqyqjw2v
  - &byteskey age1racjjdvwuara6vlx2cl2z9k3j6zcn70s49f4ged5u8w8f90txc4sxgyqnh
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *primary
      - *bitskey
      - *byteskey

